#!/usr/bin/env python3
"""Retain one real Codex baseline/Again editable pair and its raw events.

These fixed public fixtures are diagnostics, not a balanced cohort or an
acceleration qualification.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import pathlib
import shutil
import signal
import subprocess
import sys
import tempfile
import time

import agent_gateway_editable_pair as pair
from agent_gateway_authenticated_product_e2e import Client, start_daemon, structured
from agent_gateway_codex_live_probe_v1 import sha256, source_state


MAX_EVENT_BYTES = 8 * 1024 * 1024
TIMEOUT_SECONDS = 180
TASK_IDS = {
    "calculator": "calculator-fix",
    "running-balance": "running-balance-fix",
    "rust-calculator": "rust-calculator-fix",
    "js-calculator": "js-calculator-fix",
    "js-calculator-generic-validation": "js-calculator-generic-validation-fix",
    "js-package-script": "js-package-script-fix",
    "greeting-feature": "greeting-feature",
    "balance-helper": "balance-helper-fix",
    "balance-helper-large": "balance-helper-large-fix",
}


def configure_fixture(name: str) -> None:
    pair.TEST_COMMAND = ("/usr/bin/python3", "-I", "-m", "unittest", "discover", "-s", "tests", "-q")
    pair.TARGET_ORACLE_MODE = "exact"
    if name == "calculator":
        return
    if name == "rust-calculator":
        pair.TARGET_ORACLE_MODE = "behavior"
        cargo = shutil.which("cargo")
        if not cargo:
            raise RuntimeError("rust-calculator fixture requires cargo")
        # rustup dispatches from argv[0]=cargo; resolving its shim to rustup
        # changes the command's meaning.
        pair.TEST_COMMAND = (cargo, "test", "--quiet")
        pair.TARGET = "src/lib.rs"
        pair.TEST = "tests/calculator.rs"
        pair.BUGGY = "pub fn total(values: &[i32]) -> i32 {\n    values.iter().sum::<i32>() + 1\n}\n"
        pair.FIXED = pair.BUGGY.replace("sum::<i32>() + 1", "sum::<i32>()")
        pair.PROMPT = (
            "Fix the off-by-one defect in src/lib.rs so total(values) returns the sum. "
            "Preserve the public API. Do not edit tests or other files. Run cargo test, then stop."
        )
        pair.FIXTURE = {
            "Cargo.toml": '[package]\nname = "again_calculator_fixture"\nversion = "0.1.0"\nedition = "2021"\n',
            "Cargo.lock": '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "again_calculator_fixture"\nversion = "0.1.0"\n',
            pair.TARGET: pair.BUGGY,
            pair.TEST: (
                "use again_calculator_fixture::total;\n"
                "#[test]\nfn sums_values() { assert_eq!(total(&[1, 2, 3]), 6); }\n"
                "#[test]\nfn empty_is_zero() { assert_eq!(total(&[]), 0); }\n"
                "#[test]\nfn negatives() { assert_eq!(total(&[-2, 5, -1]), 2); }\n"
                "#[test]\nfn large_values() { assert_eq!(total(&[100, 200]), 300); }\n"
            ),
            "README.md": "# Calculator fixture\nRun `cargo test`.\n",
        }
        return
    if name in ("js-calculator", "js-calculator-generic-validation"):
        pair.TARGET_ORACLE_MODE = "behavior"
        node = shutil.which("node")
        if not node:
            raise RuntimeError("js-calculator fixture requires node")
        pair.TEST_COMMAND = (str(pathlib.Path(node).resolve()), "--test", "tests/test_calculator.mjs")
        pair.TARGET = "src/calculator.mjs"
        pair.TEST = "tests/test_calculator.mjs"
        pair.BUGGY = (
            "export function total(values) {\n"
            "  return values.reduce((sum, value) => sum + value, 0) + 1;\n"
            "}\n"
        )
        pair.FIXED = pair.BUGGY.replace("value, 0) + 1", "value, 0)")
        pair.PROMPT = (
            "Fix the off-by-one defect in src/calculator.mjs so total(values) returns the sum. "
            "Preserve the exported API. Do not edit tests or other files. "
            + (
                "Run the existing tests, then stop."
                if name == "js-calculator-generic-validation"
                else "Run node --test tests/test_calculator.mjs, then stop."
            )
        )
        pair.FIXTURE = {
            pair.TARGET: pair.BUGGY,
            pair.TEST: (
                "import test from 'node:test';\n"
                "import assert from 'node:assert/strict';\n"
                "import { total } from '../src/calculator.mjs';\n"
                "test('sum', () => assert.equal(total([1, 2, 3]), 6));\n"
                "test('empty', () => assert.equal(total([]), 0));\n"
                "test('negatives', () => assert.equal(total([-2, 5, -1]), 2));\n"
                "test('large values', () => assert.equal(total([100, 200]), 300));\n"
            ),
            "README.md": "# JavaScript calculator fixture\nRun `node --test tests/test_calculator.mjs`.\n",
        }
        return
    if name == "js-package-script":
        pair.TARGET_ORACLE_MODE = "behavior"
        node = shutil.which("node")
        if not node:
            raise RuntimeError("js-package-script fixture requires node")
        pair.TEST_COMMAND = (str(pathlib.Path(node).resolve()), "--test", "test/total.spec.mjs")
        pair.TARGET = "src/total.mjs"
        pair.TEST = "test/total.spec.mjs"
        pair.BUGGY = (
            "export function total(values) {\n"
            "  return values.reduce((sum, value) => sum + value, 0) + 1;\n"
            "}\n"
        )
        pair.FIXED = pair.BUGGY.replace("value, 0) + 1", "value, 0)")
        pair.PROMPT = (
            "Fix the off-by-one defect in src/total.mjs so total(values) returns the sum. "
            "Preserve the exported API. Do not edit tests or other files. "
            "Run the project's existing test script after editing, then stop."
        )
        pair.FIXTURE = {
            pair.TARGET: pair.BUGGY,
            pair.TEST: (
                "import test from 'node:test';\n"
                "import assert from 'node:assert/strict';\n"
                "import { total } from '../src/total.mjs';\n"
                "test('sum', () => assert.equal(total([1, 2, 3]), 6));\n"
                "test('empty', () => assert.equal(total([]), 0));\n"
                "test('negatives', () => assert.equal(total([-2, 5, -1]), 2));\n"
            ),
            "package.json": '{"name":"again-package-test-fixture","private":true,"type":"module","packageManager":"npm@11.0.0","scripts":{"test":"node --test test/total.spec.mjs"}}\n',
            "README.md": "# Package test fixture\n",
        }
        return
    if name == "greeting-feature":
        pair.TARGET_ORACLE_MODE = "behavior"
        pair.TARGET = "src/greeting.py"
        pair.TEST = "tests/test_greeting.py"
        pair.BUGGY = "def greet(name):\n    return f\"Hello, {name}\"\n"
        pair.FIXED = (
            "def greet(name, excited=False):\n"
            "    greeting = f\"Hello, {name}\"\n"
            "    return greeting + (\"!\" if excited else \"\")\n"
        )
        pair.PROMPT = (
            "Add an optional excited=False argument to greet(name) in src/greeting.py. "
            "When true, append exactly one exclamation mark; default calls must keep the old "
            "output. Do not edit tests or other files. Run the existing unittest suite, then stop."
        )
        pair.FIXTURE = {
            pair.TARGET: pair.BUGGY,
            pair.TEST: (
                "import importlib.util\nimport pathlib\nimport unittest\n\n"
                "ROOT = pathlib.Path(__file__).parents[1]\n"
                "SPEC = importlib.util.spec_from_file_location('greeting', ROOT / 'src/greeting.py')\n"
                "module = importlib.util.module_from_spec(SPEC)\n"
                "SPEC.loader.exec_module(module)\n\n"
                "class GreetingTests(unittest.TestCase):\n"
                "    def test_default(self):\n"
                "        self.assertEqual(module.greet('Ada'), 'Hello, Ada')\n"
                "    def test_excited(self):\n"
                "        self.assertEqual(module.greet('Ada', excited=True), 'Hello, Ada!')\n"
                "    def test_explicit_false(self):\n"
                "        self.assertEqual(module.greet('', excited=False), 'Hello, ')\n"
                "    def test_empty_excited(self):\n"
                "        self.assertEqual(module.greet('', excited=True), 'Hello, !')\n"
            ),
            "README.md": "# Greeting feature fixture\nRun `python3 -m unittest discover -s tests`.\n",
        }
        return
    if name in ("balance-helper", "balance-helper-large"):
        pair.TARGET = "src/util.py"
        pair.TEST = "tests/test_ledger.py"
        pair.BUGGY = "def adjust_total(value):\n    return value + 1\n"
        pair.FIXED = "def adjust_total(value):\n    return value\n"
        if name == "balance-helper-large":
            context = "# Ledger totals use this helper at the final boundary.\n" * 30
            pair.BUGGY += "\n" + context
            pair.FIXED += "\n" + context
        pair.PROMPT = (
            "Fix the off-by-one total reported by src/ledger.py. Keep ledger.py's "
            "delegation to its helper and correct the underlying implementation. "
            "Do not edit tests or unrelated files. Run the existing unittest suite, then stop."
        )
        pair.FIXTURE = {
            "src/ledger.py": (
                "from util import adjust_total\n\n"
                "def total(values):\n"
                "    return adjust_total(sum(values))\n"
            ),
            pair.TARGET: pair.BUGGY,
            pair.TEST: (
                "import pathlib\nimport sys\nimport unittest\n\n"
                "ROOT = pathlib.Path(__file__).parents[1]\n"
                "sys.path.insert(0, str(ROOT / 'src'))\n"
                "from ledger import total\n\n"
                "class LedgerTests(unittest.TestCase):\n"
                "    def test_sum(self):\n"
                "        self.assertEqual(total([1, 2, 3]), 6)\n"
                "    def test_empty(self):\n"
                "        self.assertEqual(total([]), 0)\n"
                "    def test_negative(self):\n"
                "        self.assertEqual(total([-2, 5, -1]), 2)\n"
            ),
            "README.md": "# Ledger fixture\nRun `python3 -m unittest discover -s tests`.\n",
        }
        return
    if name != "running-balance":
        raise RuntimeError(f"unknown fixture: {name}")
    pair.TARGET = "src/running_balance.py"
    pair.TEST = "tests/test_running_balance.py"
    pair.BUGGY = (
        "def balances(opening, changes):\n"
        "    current = opening\n"
        "    result = []\n"
        "    for change in changes:\n"
        "        result.append(current)\n"
        "        current += change\n"
        "    return result\n"
    )
    pair.FIXED = pair.BUGGY.replace(
        "        result.append(current)\n        current += change\n",
        "        current += change\n        result.append(current)\n",
    )
    pair.PROMPT = (
        "Fix src/running_balance.py so balances(opening, changes) reports each "
        "balance after applying that change. Keep the API and order. Do not edit "
        "tests or other files. Run the existing test suite, then stop."
    )
    pair.FIXTURE = {
        pair.TARGET: pair.BUGGY,
        pair.TEST: (
            "import importlib.util\n"
            "import pathlib\n"
            "import unittest\n\n"
            "ROOT = pathlib.Path(__file__).parents[1]\n"
            "SPEC = importlib.util.spec_from_file_location('running_balance', ROOT / 'src/running_balance.py')\n"
            "module = importlib.util.module_from_spec(SPEC)\n"
            "SPEC.loader.exec_module(module)\n\n"
            "class BalanceTests(unittest.TestCase):\n"
            "    def test_increases_and_decreases(self):\n"
            "        self.assertEqual(module.balances(10, [3, -2, 5]), [13, 11, 16])\n"
            "    def test_empty(self):\n"
            "        self.assertEqual(module.balances(10, []), [])\n\n"
            "if __name__ == '__main__':\n"
            "    unittest.main()\n"
        ),
        "README.md": "# Again running balance editable benchmark fixture\n",
    }


def again_instruction(task_id: str) -> str:
    return (
        "Use Again MCP for repository reads and shared task context. Call task.start "
        f"with taskId {task_id}, includeSourcePreviews=true, and task {json.dumps(pair.PROMPT)}. "
        "Use complete digest-checked sourcePreviews in the task.start response. "
        "Call repo.read only for relevant files without a complete preview, or when current bytes "
        "are needed after an ambiguous edit. Then "
    )


def seed_prior_brain(binary: pathlib.Path, workspace: pathlib.Path,
                     decoy_count: int = 0, search: bool = False) -> dict[str, str | int]:
    """Create prior checked source observations through the real Again launcher."""
    read_range = "1,200p" if len(pair.BUGGY) > 256 else "1,20p"
    if search:
        event_script = (
            "output = ''\n"
            "for path in ('src/ledger.py', target):\n"
            "    for number, line in enumerate((workspace / path).read_text().splitlines(), 1):\n"
            "        if 'adjust_total' in line:\n"
            "            output += f'{path}:{number}:{line}\\n'\n"
            "print(json.dumps({'type':'item.completed','item':{'id':'prior_search','type':'command_execution',"
            "'command':'rg -n -F adjust_total src','aggregated_output':output,'exit_code':0,'status':'completed'}}))\n"
        )
    else:
        event_script = (
            "content = (workspace / target).read_text()\n"
            "print(json.dumps({'type':'item.completed','item':{'id':'prior_read','type':'command_execution',"
            f"'command':\"sed -n '{read_range}' \" + target,'aggregated_output':content,'exit_code':0,'status':'completed'}}}}))\n"
        )
    with tempfile.TemporaryDirectory(prefix="again-prior-task-") as temporary:
        fake_bin = pathlib.Path(temporary)
        fake_codex = fake_bin / "codex"
        fake_codex.write_text(
            "#!/usr/bin/env python3\n"
            "import json, pathlib, sys\n"
            f"target = {pair.TARGET!r}\n"
            "workspace = pathlib.Path(sys.argv[sys.argv.index('-C') + 1])\n"
            + event_script
            + "print(json.dumps({'type':'item.completed','item':{'id':'done','type':'agent_message','text':'Done'}}))\n"
        )
        fake_codex.chmod(0o700)
        environment = os.environ.copy()
        environment["PATH"] = str(fake_bin) + os.pathsep + environment["PATH"]
        result = subprocess.run(
            [str(binary), "codex", "--workspace", str(workspace),
             "--task-id", "prior-ledger-investigation",
             "--task", "Investigate ledger balance helper behavior", "--", "--ephemeral"],
            cwd=workspace, env=environment, capture_output=True, text=True, timeout=30,
        )
        if result.returncode != 0:
            raise RuntimeError(f"could not seed prior Brain task: {result.stderr[-1000:]}")
    brain = subprocess.run(
        [str(binary), "brain", "show", "--workspace", str(workspace)],
        cwd=workspace, capture_output=True, text=True, check=True, timeout=10,
    )
    observations = json.loads(brain.stdout)["fileObservations"]
    if pair.TARGET not in {item["path"] for item in observations}:
        raise RuntimeError("prior Brain source read was not recorded")
    if decoy_count:
        for index in range(decoy_count):
            if not (workspace / "src" / "background" / f"module_{index:04}.py").is_file():
                raise RuntimeError("prior Brain decoy file is missing")
        with tempfile.TemporaryDirectory(prefix="again-prior-decoys-") as temporary:
            fake_bin = pathlib.Path(temporary)
            fake_codex = fake_bin / "codex"
            fake_codex.write_text(
                "#!/usr/bin/env python3\n"
                "import json, pathlib, sys\n"
                "workspace = pathlib.Path(sys.argv[sys.argv.index('-C') + 1])\n"
                f"for index in range({decoy_count}):\n"
                "    path = f'src/background/module_{index:04}.py'\n"
                "    content = (workspace / path).read_text()\n"
                "    item = {'id':f'decoy_{index}', 'type':'command_execution', "
                "'command':'cat ' + path, 'aggregated_output':content, 'exit_code':0, 'status':'completed'}\n"
                "    print(json.dumps({'type':'item.completed', 'item':item}))\n"
            )
            fake_codex.chmod(0o700)
            environment = os.environ.copy()
            environment["PATH"] = str(fake_bin) + os.pathsep + environment["PATH"]
            result = subprocess.run(
                [str(binary), "codex", "--workspace", str(workspace),
                 "--task-id", "prior-background-investigation",
                 "--task", "Inspect background module values", "--", "--ephemeral"],
                cwd=workspace, env=environment, capture_output=True, text=True, timeout=60,
            )
            if result.returncode != 0:
                raise RuntimeError(f"could not seed unrelated Brain reads: {result.stderr[-1000:]}")
    return {"taskId": "prior-ledger-investigation", "path": pair.TARGET,
            "sourceSha256": hashlib.sha256((workspace / pair.TARGET).read_bytes()).hexdigest(),
            "decoyCount": decoy_count, "mode": "search" if search else "read"}


def run_condition(
    condition: str, workspace: pathlib.Path, binary: pathlib.Path, model: str,
    task_id: str,
    source_files: int = 0,
    task_start_only_surface: bool = False,
    compact_task_result: bool = False,
    prebrief_with_mcp: bool = False,
    seed_brain: bool = False,
    brain_decoys: int = 0,
    seed_brain_search: bool = False,
    required_agent_validation: tuple[str, ...] = (),
) -> tuple[dict[str, object], bytes]:
    pair.MAX_FIXTURE_FILES = max(pair.MAX_FIXTURE_FILES, source_files + len(pair.FIXTURE) + 8)
    pair.create_fixture(workspace)
    if source_files:
        background = workspace / "src" / "background"
        background.mkdir()
        for index in range(source_files):
            (background / f"module_{index:04}.py").write_text(
                f"value = {index}\n", encoding="utf-8"
            )
    before = pair.snapshot(workspace)
    prior_brain = seed_prior_brain(binary, workspace, brain_decoys, seed_brain_search) if seed_brain and condition == "product" else None
    stats_before = pair.again_stats(binary, workspace)
    preparation_ms = 0.0
    initial_brief = ""
    if condition == "prebrief":
        preparation_started = time.monotonic()
        environment = os.environ.copy()
        daemon = start_daemon(binary, workspace, environment)
        client = Client(binary, workspace, environment)
        try:
            brief = structured(client.tool("task.start", {
                "taskId": task_id, "task": pair.PROMPT,
                "includeSourcePreviews": True,
                "previewOnly": True,
            }), "precomputed task brief")
        finally:
            client.close()
        previews = brief.get("sourcePreviews", [])
        if not previews or not all(item.get("complete") is True for item in previews):
            raise RuntimeError("precomputed brief lacked complete source previews")
        initial_brief = (
            "Again verified these complete source previews before this task. "
            "They are current until you edit the files. Use them to make the repair; "
            "run validation after editing.\n"
            + "\n".join(
                f"FILE {item['path']} DIGEST {item['sourceDigest']}\n{item['text']}"
                for item in previews
            )
            + "\nVALIDATION " + json.dumps(brief.get("validationPreview")) + "\n"
        )
        preparation_ms = round((time.monotonic() - preparation_started) * 1000, 3)
    codex = pathlib.Path(subprocess.run(
        ["which", "codex"], capture_output=True, text=True, check=True
    ).stdout.strip()).resolve(strict=True)
    command = [
        str(codex), "exec", "--ephemeral", "--ignore-user-config", "--json",
        "--approve-for-me", "-m", model, "-C", str(workspace),
    ]
    if condition in ("product", "product-cold"):
        command = [
            str(binary), "codex", "--workspace", str(workspace),
            "--task-id", task_id, "--task", pair.PROMPT, "--",
            "--ephemeral", "--ignore-user-config", "--json",
            "--approve-for-me", "-m", model,
        ]
    if condition == "again" or (condition == "prebrief" and prebrief_with_mcp):
        if task_start_only_surface or compact_task_result:
            bridge = pathlib.Path(__file__).with_name("agent_gateway_codex_task_start_surface_v1.py").resolve()
            server_command = sys.executable
            server_args = [str(bridge), "--binary", str(binary), "--workspace", str(workspace)]
            if task_start_only_surface:
                server_args.append("--task-start-only")
            if compact_task_result:
                server_args.append("--compact-task-result")
        else:
            server_command = str(binary)
            server_args = ["mcp", "connect", "--workspace", str(workspace)]
        command += [
            "-c", f"mcp_servers.again.command={json.dumps(server_command)}",
            "-c", f"mcp_servers.again.args={json.dumps(server_args)}",
        ]
    if condition not in ("product", "product-cold"):
        command.append((again_instruction(task_id) if condition == "again" else initial_brief) + pair.PROMPT)
    original = hashlib.sha256((workspace / pair.TARGET).read_bytes()).digest()
    with tempfile.TemporaryFile() as stdout, tempfile.TemporaryFile() as stderr:
        started = time.monotonic()
        process = subprocess.Popen(
            command, cwd=workspace, stdin=subprocess.DEVNULL, stdout=stdout, stderr=stderr,
            start_new_session=True
        )
        first_edit_ms = None
        timed_out = False
        event_timeline = []
        event_offset = 0
        pending_event_bytes = b""

        def sample_events() -> None:
            nonlocal event_offset, pending_event_bytes
            while event_offset < MAX_EVENT_BYTES:
                chunk = os.pread(stdout.fileno(), min(65536, MAX_EVENT_BYTES - event_offset), event_offset)
                if not chunk:
                    break
                event_offset += len(chunk)
                pending_event_bytes += chunk
                lines = pending_event_bytes.split(b"\n")
                pending_event_bytes = lines.pop()
                for line in lines:
                    try:
                        event = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    kind = event.get("type")
                    item = event.get("item") or {}
                    if kind == "turn.completed" or (
                        kind in ("item.started", "item.completed")
                        and item.get("type") in ("file_change", "command_execution")
                    ):
                        if len(event_timeline) < 256:
                            event_timeline.append({
                                "elapsedMs": round((time.monotonic() - started) * 1000 + preparation_ms, 3),
                                "event": kind,
                                "itemId": item.get("id"),
                                "itemType": item.get("type"),
                            })

        while process.poll() is None:
            sample_events()
            elapsed = time.monotonic() - started
            if elapsed >= TIMEOUT_SECONDS:
                timed_out = True
                os.killpg(process.pid, signal.SIGKILL)
                break
            target = workspace / pair.TARGET
            if first_edit_ms is None and target.is_file() and hashlib.sha256(target.read_bytes()).digest() != original:
                first_edit_ms = round(elapsed * 1000 + preparation_ms, 3)
            time.sleep(0.02)
        returncode = process.wait(timeout=10)
        sample_events()
        codex_elapsed_ms = round((time.monotonic() - started) * 1000, 3)
        elapsed_ms = round(codex_elapsed_ms + preparation_ms, 3)
        if first_edit_ms is None and (workspace / pair.TARGET).is_file() and hashlib.sha256((workspace / pair.TARGET).read_bytes()).digest() != original:
            first_edit_ms = elapsed_ms
        stdout.seek(0)
        stderr.seek(0)
        raw = stdout.read(MAX_EVENT_BYTES + 1)
        stderr_bytes = stderr.read(MAX_EVENT_BYTES + 1)
    captured = len(raw) <= MAX_EVENT_BYTES and len(stderr_bytes) <= MAX_EVENT_BYTES
    events = []
    completed = []
    usage = None
    turn_completed_count = 0
    if captured:
        for line in raw.splitlines():
            try:
                event = json.loads(line)
            except json.JSONDecodeError:
                continue
            events.append(event)
            item = event.get("item") or {}
            if event.get("type") == "item.completed" and item.get("type") in (
                "mcp_tool_call", "command_execution", "file_change"
            ):
                completed.append({
                    "type": item.get("type"),
                    "tool": item.get("tool"),
                    "status": item.get("status"),
                    "resultBytes": len(json.dumps(item.get("result"), separators=(",", ":")).encode())
                    if item.get("result") is not None else None,
                    "command": str(item.get("command", ""))[:300],
                    "exitCode": item.get("exit_code"),
                })
            if event.get("type") == "turn.completed":
                usage = event.get("usage")
                turn_completed_count += 1
    oracle = (
        pair.validate_edit(workspace, before, 30)
        if (workspace / pair.TARGET).is_file()
        else {"passed": False, "reason": "target_missing"}
    )
    agent_validation_observed = any(
        action["type"] == "command_execution"
        and action["exitCode"] == 0
        and any(selector in action["command"] for selector in required_agent_validation)
        for action in completed
    ) if required_agent_validation else None
    stats_after = pair.again_stats(binary, workspace)
    stats = {key: stats_after[key] - stats_before[key] for key in stats_before}
    brain_run = None
    if condition in ("product", "product-cold"):
        brain = subprocess.run(
            [str(binary), "brain", "show", "--workspace", str(workspace)],
            cwd=workspace, capture_output=True, text=True, check=True, timeout=10,
        )
        matching_runs = [run for run in json.loads(brain.stdout)["recentRuns"]
                         if run["task_id"] == task_id]
        if len(matching_runs) != 1:
            raise RuntimeError("Codex launcher did not retain exactly one current Brain run")
        brain_run = matching_runs[0]
        if brain_run["exit_code"] != returncode or brain_run["turn_completed"] is not True:
            raise RuntimeError("retained Brain run omitted the completed Codex outcome")
        if turn_completed_count == 1 and usage is not None and any(brain_run[field] != usage[source] for field, source in (
            ("input_tokens", "input_tokens"),
            ("cached_input_tokens", "cached_input_tokens"),
            ("output_tokens", "output_tokens"),
        )):
            raise RuntimeError("retained Brain usage disagrees with the raw Codex event stream")
    if condition in ("again", "prebrief", "product", "product-cold"):
        subprocess.run(
            [str(binary), "mcp", "daemon", "stop", "--workspace", str(workspace)],
            capture_output=True, text=True, timeout=10
        )
        if condition == "prebrief":
            daemon.wait(timeout=10)
            if daemon.stderr is not None:
                daemon.stderr.close()
    result = {
        "condition": condition,
        "exitCode": returncode,
        "timedOut": timed_out,
        "eventsCaptured": captured,
        "elapsedMs": elapsed_ms,
        "preparationMs": preparation_ms,
        "codexElapsedMs": codex_elapsed_ms,
        "eventTimeline": event_timeline,
        "firstEditMs": first_edit_ms,
        "rawEventBytes": len(raw),
        "rawEventSha256": hashlib.sha256(raw).hexdigest(),
        "stderrSha256": hashlib.sha256(stderr_bytes).hexdigest(),
        "eventCount": len(events),
        "completedActions": completed,
        "usage": usage,
        "oracle": oracle,
        "agentValidationObserved": agent_validation_observed,
        "againStatsDelta": stats,
        "priorBrain": prior_brain,
        "brainRun": brain_run,
    }
    return result, raw


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binary", type=pathlib.Path, default="target/debug/again")
    parser.add_argument("--model", default="gpt-6-sol")
    parser.add_argument("--fixture", choices=tuple(TASK_IDS), default="calculator")
    parser.add_argument("--source-files", type=int, default=0)
    parser.add_argument("--order", choices=("baseline-first", "again-first"), default="baseline-first")
    parser.add_argument("--prebrief", action="store_true",
                        help="diagnostic: prepare the verified task brief before launching Codex")
    parser.add_argument("--product-wrapper", action="store_true",
                        help="diagnostic: launch through the production again codex command")
    parser.add_argument("--seed-prior-brain", action="store_true",
                        help="seed a verified prior source read for a balance-helper returning task")
    parser.add_argument("--seed-prior-brain-search", action="store_true",
                        help="seed verified prior source matches for a balance-helper returning task")
    parser.add_argument("--required-agent-validation", action="append", default=[],
                        help="require a completed zero-exit agent test call containing this fixed command text")
    parser.add_argument("--prebrief-with-mcp", action="store_true",
                        help="diagnostic: keep the normal Again MCP connection available after prebrief")
    parser.add_argument("--task-start-only-surface", action="store_true",
                        help="diagnostic: advertise only task.start while forwarding through the authenticated daemon")
    parser.add_argument("--compact-task-result", action="store_true",
                        help="diagnostic: shorten the text payload while preserving structuredContent")
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()
    configure_fixture(args.fixture)
    if not 0 <= args.source_files <= 1000:
        parser.error("--source-files must be between 0 and 1000")
    if args.prebrief_with_mcp and not args.prebrief:
        parser.error("--prebrief-with-mcp requires --prebrief")
    if args.product_wrapper and (args.prebrief or args.prebrief_with_mcp):
        parser.error("--product-wrapper cannot be combined with diagnostic prebrief modes")
    if args.seed_prior_brain and args.seed_prior_brain_search:
        parser.error("select only one prior Brain seed mode")
    if (args.seed_prior_brain or args.seed_prior_brain_search) and (not args.product_wrapper or args.fixture not in ("balance-helper", "balance-helper-large")):
        parser.error("prior Brain seeding requires --product-wrapper and a balance-helper fixture")
    binary = args.binary.resolve(strict=True)
    connector = subprocess.run(
        [str(binary), "mcp", "connect", "--help"],
        capture_output=True, text=True, timeout=5,
    )
    if connector.returncode != 0:
        parser.error("--binary must be built with the daemon feature (cargo build --features daemon)")
    root = pathlib.Path(__file__).resolve().parents[1]
    source_before_run = source_state(root, binary)
    codex = pathlib.Path(subprocess.run(
        ["which", "codex"], capture_output=True, text=True, check=True
    ).stdout.strip()).resolve(strict=True)
    version = subprocess.run([str(codex), "--version"], capture_output=True, text=True, check=True).stdout.strip()
    observations = []
    args.output.parent.mkdir(parents=True, exist_ok=True)
    treatment = "product" if args.product_wrapper else "prebrief" if args.prebrief else "again"
    order = ("baseline", treatment) if args.order == "baseline-first" else (treatment, "baseline")
    for condition in order:
        with tempfile.TemporaryDirectory(prefix=f"again-codex-pair-{condition}-") as temporary:
            result, raw = run_condition(
                condition, pathlib.Path(temporary), binary, args.model,
                TASK_IDS[args.fixture],
                args.source_files, args.task_start_only_surface, args.compact_task_result,
                args.prebrief_with_mcp, args.seed_prior_brain or args.seed_prior_brain_search,
                seed_brain_search=args.seed_prior_brain_search,
                required_agent_validation=tuple(args.required_agent_validation),
            )
        raw_path = args.output.with_name(args.output.stem + f"-{condition}.jsonl")
        raw_path.write_bytes(raw)
        result["rawEventFile"] = raw_path.name
        observations.append(result)
    accepted = all(
        result["exitCode"] == 0 and not result["timedOut"]
        and result["eventsCaptured"] and result["oracle"]["passed"]
        and result["agentValidationObserved"] is not False
        for result in observations
    ) and next(result for result in observations if result["condition"] == "baseline")["againStatsDelta"]["requested"] == 0
    report = {
        "schema": "again.codex-editable-pair-diagnostic.v1",
        "recordedAtUtc": dt.datetime.now(dt.timezone.utc).isoformat(),
        "evidenceScope": "one unbalanced local pair, not acceleration qualification",
        "codexVersion": version,
        "codexBinarySha256": sha256(codex),
        "againBinarySha256": sha256(binary),
        "harnessSha256": sha256(pathlib.Path(__file__)),
        "source": source_before_run,
        "model": args.model,
        "fixture": args.fixture,
        "sourceFiles": args.source_files,
        "approvalMode": "approve-for-me",
        "fixtureSha256": hashlib.sha256(pair.canonical_bytes(pair.FIXTURE)).hexdigest(),
        "promptSha256": hashlib.sha256(pair.PROMPT.encode()).hexdigest(),
        "order": list(order),
        "surface": ("product-wrapper" if args.product_wrapper else
                    "prebrief-with-mcp" if args.prebrief_with_mcp else
                    "prebrief-no-mcp" if args.prebrief else
                    "task-start-only-diagnostic" if args.task_start_only_surface else "full"),
        "compactTaskResult": args.compact_task_result,
        "prebrief": args.prebrief,
        "prebriefWithMcp": args.prebrief_with_mcp,
        "returningTask": args.seed_prior_brain or args.seed_prior_brain_search,
        "requiredAgentValidation": args.required_agent_validation,
        "observations": observations,
        "accepted": accepted,
    }
    args.output.write_text(json.dumps(report, sort_keys=True, indent=2) + "\n")
    print(json.dumps({"accepted": accepted, "output": str(args.output)}))
    return 0 if accepted else 1


if __name__ == "__main__":
    raise SystemExit(main())
